<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\ImportUsersType;
use App\Form\UserUpdateType;
use App\Repository\SitesRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;

class UserController extends AbstractController
{
    #[Route('/user/update', name: 'user_update')]
    public function update(Request $request,UserPasswordHasherInterface $userPasswordHasher,EntityManagerInterface $entityManager,UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $userForm = $this->createForm(UserUpdateType::class,$user);
        $userForm->handleRequest($request);

        if($userForm->isSubmitted()){
            if($userForm->get('password')->getData() != null) {
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $userForm->get('password')->getData()
                    )
                );
            }
            $entityManager->flush();
        }

        return $this->render('user/index.html.twig', [
            'userForm' => $userForm->createView()
        ]);
    }

    #[Route('/user/detail/{id}', name: 'user_detail')]
    public function detail($id, Request $request, UserRepository $userRepository): Response
    {

        $user = $userRepository->find($id);

        if (!$user) {
            return $this->redirectToRoute('sortie_liste');
        }



        return $this->render('user/userDetail.html.twig', [
            'user' => $user
        ]);
    }
    #[Route('/user/upload', name: 'user_upload')]
    public function importAction(Request $request,EntityManagerInterface $entityManager,SitesRepository $sitesRepository,UserPasswordHasherInterface $userPasswordHasher)
    {
        $form = $this->createForm(ImportUsersType::class);
        $form->handleRequest($request);

        $arrayOfErrrors = [];
        $i =0;
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $file */
            $file = $form->get('file')->getData();

            // Move the file to the directory where CSV files are stored
            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
            $file->move(
                'public/upload',
                $fileName
            );

            // Read the CSV file and do something with the data
            $csv = array_map('str_getcsv', file('public/upload'.'/'.$fileName));

            foreach ($csv as &$ligne) {
                if($i == 0) {
                    $i++;
                    continue;
                }

                $separer = explode(";",$ligne[0]);
                dump(count($separer));
                if(count($separer) != 7){
                    $i++;
                    $arrayOfErrrors[] = "Erreur lors de la tentative de création de l'utilisateur à la ligne " . $i . " . Veuillez vérifier les informations de l'utilisateur.";
                    continue;
                }
                $user = new User();
                $user->setEmail($separer[0]);
                $user->setPassword(
                    $userPasswordHasher->hashPassword(
                        $user,
                        $separer[1]
                    )
                );
                $user->setNom($separer[2]);
                $user->setPrenom($separer[3]);
                $user->setPseudo($separer[4]);
                $user->setTelephone($separer[5]);

                $siteObj = $sitesRepository->findByName($separer[6]);

                $user->setSites($siteObj);

                $entityManager->persist($user);
                $entityManager->flush();
                $i++;
            }
        }
        dump($arrayOfErrrors);
        foreach ($arrayOfErrrors as &$errror) {
            $this->addFlash("notice", $errror);
        }
        return $this->render('user/import.html.twig', [
            'Importform' => $form->createView(),
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
